### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by AWehrhahn** [rhdtownsend/msg#9]
Following the instructions here: https://msg.readthedocs.io/en/latest/user-guide/quick-start.html#quick-start
the installation fails at the final compilation step. I have tracked it down to some misplaced files in src/forum.

Link to Review thread: https://github.com/openjournals/joss-reviews/issues/4602

**Comment by ivastar** [comment]
Following up on the review by @AWehrhahn, I was also unable to complete the installation via the instructions. The directory structure is not what the make file expects. I was able to install directly the current version from the repository. A possible solution would be to direct used to installing from a specific commit rather (e.g., [this example](https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip)) rather than from a tar file.

**Comment by rhdtownsend** [comment]
It looks like there was a mistake in creating the tarball for the 1.0 release (goodness knows how that happened, I though I had checked it). I fixed this and reissued the tarball on 8/24/22.
